### ISSUE TITLE
Feature request - options panel

### ISSUE THREAD

**Issue by eighthday** [rsms/WebView-OSX-Screensaver#1]
This is really useful, thanks. 

I wonder if you could include an example of how set a simple option field and pass it through to the html ?

**Comment by rsms** [comment]
What is an "option field"?

**Comment by eighthday** [comment]
So you can have a user setting (e.g show clock), accessible under the screensaver in system preferences: 

![screen shot 2014-06-19 at 10 30 44](https://cloud.githubusercontent.com/assets/4104767/3325831/6e7500fa-f794-11e3-8d82-a1cd2d0ee104.png)

**Comment by rsms** [comment]
Oh, I see. Have a look through [the documentation](https://developer.apple.com/library/mac/documentation/UserExperience/Reference/ScreenSaver/ObjC_classic/_index.html) — in [`WSView.m`](https://github.com/rsms/WebView-OSX-Screensaver/blob/master/WSView.m#L23) you'll need to implement `- (BOOL)hasConfigureSheet` and `- (NSWindow *)configureSheet`, the former should return `YES` and the latter a `NSWindow` (you can either make one programmatically or using the interface builder.) The window is what will be used for a configuration sheet in System Preferences. Make sure to include a "done" button that closes the window by calling endSheet on NSApp.

There are many ways to create this window, like using a nib file, with or without using bindings, or ibactions, etc. Just google it. There are surely plenty of guides.

From there you can store your preferences in ScreenSaverDefaults and add a bit of code to `WSView.m`':

Under `#pragma mark - WebFrameLoadDelegate`, add this:

``` mm
- (void)webView:(WebView*)sender didClearWindowObject:(WebScriptObject*)windowObject forFrame:(WebFrame*)frame {
  ScreenSaverDefaults* config = [ScreenSaverDefaults defaultsForModuleWithName:[NSBundle bundleForClass:[self class]].bundleIdentifier];
  NSError* json_encoding_error;
  NSData* json_data = [NSJSONSerialization dataWithJSONObject:config.dictionaryRepresentation options:0 error:&json_encoding_error];
  if (!json_data) {
    NSLog(@"Failed to encode user defaults as JSON: %@", json_encoding_error);
  } else {
    [windowObject evaluateWebScript:[NSString stringWithFormat:@"this.config = %@", [[NSString alloc] initWithData:json_data encoding:NSUTF8StringEncoding]]];
  }
}
```

Note that this code uses the screen saver bundle identifier for "user defaults" identity. I.e. to get a handle to the "defaults" for your screensaver:

``` mm
[ScreenSaverDefaults defaultsForModuleWithName:[NSBundle bundleForClass:[self class]].bundleIdentifier]
```
